### ISSUE TITLE
Clean default configuration

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware-contrib/invenio-matcher#1]
By default we can not make any assumption on the possible queries. So would be better to move the current configuration example into a comment, and just leave empty brakets as default. (possibly catching this in the code and raising appropriate error).

**Comment by jacquerie** [comment]
> possibly catching this in the code and raising appropriate error

I did! https://github.com/inspirehep/invenio-matcher/blob/53059dcce24b8eec91915aa504a9124e9769859b/invenio_matcher/api.py#L36-L37

Ok, maybe `TODO` isn't very informative as an error message...
