### ISSUE TITLE
mlt query does not support min_score

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/invenio-matcher#17]
Even though `_build_mlt_query` uses `min_score` (https://github.com/inveniosoftware-contrib/invenio-matcher/blob/master/invenio_matcher/engine.py#L121-L136) trying locally I see that in ES@2.4 

```
"reason": "[mlt] query does not support [min_score]",
```

**Comment by jacquerie** [comment]
I think we agreed here that you mistyped the query with `min_score` inside the `mlt` instead of outside, and this made it fail, so in https://github.com/inveniosoftware-contrib/invenio-matcher/issues/18 I preserved it.
