### ISSUE TITLE
Allow passing a JSON document to fuzzy queries

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/invenio-matcher#19]
When doing a fuzzy query (with underlying ES mlt query) it is useful to pass from the outside a whole JSON document to match against.

Currently this is not possible.

Also the `match` parameter is mandatory, but passing the whole JSON document makes it unnecessary for fuzzy queries.

**Comment by jacquerie** [comment]
Closed by https://github.com/inveniosoftware-contrib/invenio-matcher/pull/23.
