### ISSUE TITLE
RFC: Matcher architecture proposal

### ISSUE THREAD

**Issue by jacquerie** [inveniosoftware-contrib/invenio-matcher#2]
# Matcher

Matcher is a small module that handles exactly one problem: deciding if we
already have a record or not. Matcher solves this by running configurable
searches against our collection.
## API

The API offered is a `match` method with signature

``` python
match(record, queries=None, **kwargs)
```

The idea is that the API should be agnostic of implementation-required
parameters (like `index` or `doc_type` for Elasticsearch). These keyword
arguments are just passed down to the actual implementation.

`match` is a generator, which returns one result at a time. The result is of
class `MatchResult`, which abstracts the actual result returned by the engine in
some uniform representation. At the bare minimum, it must contain the record
that matches and a `score`, which will represent what the engine thinks is the
accuracy of the match.

---
#### Note

Callers that assume Elasticsearch will find tedious to write something like

``` python
match(r, index='records', doc_type='record')
```

every single time; the idea is to encourage them to define a method with a signature such as:

``` python
match_record(r)
```

which wraps the previous `kwargs`. In this way, if the Elasticsearch assumption they made changes, they only have to modify a single method.
## Configuration

Main configuration variables are:

``` python
MATCHER_ENGINE
```

which denotes the engine that we are using, among a set of engines dynamically
collected by `registry.py`.

We also have:

``` python
MATCHER_QUERIES
```

which denotes the list of queries that we are going to run, given a `MATCHER_ENGINE`. For example:

``` python
MATCHER_QUERIES = {
    'es': {
        'records': {
            'record': [
                ...
            ],
            'workflow': [
                ...
            ]
        }
    }
}
```

denotes the lists of queries that we want to run on the Elasticsearch engine for a document with `index=records` and `doc_type` one between `record` and `workflow`.

We only require that `MATCHER_QUERIES` is a dictionary with keys the possible
engines; the values are left to the discretion of the user of the library. In
fact, the queries are intended to be fetched using the `get_queries` method,
which receives the user passed keyword arguments.

By default, `MATCHER_QUERIES` is an empty dictionary (addresses #1).

---
#### Note

We leave `MATCHER_QUERIES`'s structure deliberately undefined because the nested
dictionary approach might make sense only for Elasticsearch; other engines might
call for a different structure.
## Query syntax

Each query is a dictionary, in which only the `type` and `match` keys are required. Here's an example:

``` python
{
    'type': 'exact',
    'match': 'report_numbers.value'
}
```

This query will extract all values from the incoming record that match the path
`'report_numbers.value`, and search for records that have _any_ of those values
as a value of `report_numbers.value`. Put in another way, the semantics are
those of an "or" query on those values.

The optional `with` key allows to specify in which path we want to search for
those values. For example:

``` python
{
    'type': 'exact',
    'match': 'titles.title',
    'with': 'old_titles.title'
}
```

This query will extract all values from the incoming record that match the path
`titles.title` and search for records that have _any_ of those values as a value
of `old_titles.title`.

---
#### Note

All other keys are optional. This can be used to pass values to the engine,
which will know how to understand them and achieve implementation-specific
behavior. For example, a `min_score` key could be added, which will then be
interpreted by the Elasticsearch engine as [the top-level `min_score`
parameter](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-request-min-score.html).

---

We propose three types of queries, called **exact**, **fuzzy** and **free**.
### Exact queries

Exact queries favor precision over recall. They require exact matching between
one of the values extracted from the incoming record and the appropriate values
from the collection.

In the case of Elasticsearch, this might be realized by an OR of term queries on
fields that were not analyzed. Matcher has no way to enforce proper
Elasticsearch configuration, which will have to be responsibility of the
administrator.
### Fuzzy queries

Fuzzy queries favor recall over precision. Their behavior is left unspecified,
but it could be modeled like Elasticsearch's `more_like_this` query.
### Free queries

Free queries allow administrators to define their own queries. They have an
additional `query` parameter that contains the query to be passed to the
underlying engine, expressed in a suitable syntax; in the worst case, it will be
an opaque string.

---
#### Note

Elasticsearch queries have to be parametrized to be useful. Creating a general
DSL that allows to build general parametrized Elasticsearch queries is a huge
endeavour, which we don't think it's worth pursuing. Instead, we propose to just
have functions, which will be called with the extracted parameters as keyword
arguments.

For example, the query:

``` python
{
    'type': 'free',
    'match': 'titles.title',
    'query': 'invenio_matcher.matchext.es:title_query',
    'foo': 'bar'
}
```

will result in the invocation of

``` python
title_query(match=titles, with='titles.title', foo='bar')
```

which will build the appropriate query.

CC: @jalavik @kaplun @lilykos

**Comment by jalavik** [comment]
Looks like a good start. Thanks @jacquerie!

I suspect we may have to enhance the result handling part to offer optional ways to validate matches like the legacy BibMatch. Search results often contain more then one possible hit, so the ability to go over every result and validate particular parts against the incoming record becomes a useful way of increasing accuracy.

Other lessons learned while doing this in the past was on the difficulty of tweaking the metadata used in the queries (from the incoming record), but we'll see how we can leverage a more complete search engine with advanced query methods on our more tricky use cases.

**Comment by jacquerie** [comment]
Regarding the first, I propose to add a keyword argument `validator` to the API:

``` python
match(record, queries=None, validator=None, **kwargs)
```

`validator` is a callback function that is run with arguments the original record and the candidate duplicate found.

Regarding the second, I'm confident that Elasticsearch can handle out of the box most of the tokenization/sanitization issues that BibMatch had to solve. On the other hand, we need to document the configuration that Elasticsearch must have in order to work as intended, as in https://github.com/inspirehep/inspire-next/issues/276.

**Comment by jalavik** [comment]
Sounds good. It would be good if the additional information returned by the search result is also part of the arguments to the `validator` function. E.g. Elasticsearch gives `_score` and perhaps other interesting information.

**Comment by jacquerie** [comment]
Oh, right: what `validator` gets is in fact the `MatchResult` class, which contains both the record, the score and other metadata.

**Comment by jalavik** [comment]
@jacquerie :+1:
