### ISSUE TITLE
_get_values maximum recursion depth exceeded when key not present

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/invenio-matcher#22]
https://github.com/inveniosoftware-contrib/invenio-matcher/blob/master/invenio_matcher/core.py#L88

Sample record:

```
{
    "titles": [{'source': 'Springer', 'title': 'Translational and Rotational Properties of Tensor Fields in Relativistic Quantum Mechanics'}],
    "dois": [{'source': 'Springer', 'value': '10.1007/s00006-015-0540-2'}]
}
```

And passing match: `dois.value.raw`

**Comment by jacquerie** [comment]
I cannot reproduce this... See: https://github.com/jacquerie/invenio-matcher/commit/5e484972b13894b307c336ced6a5721c62d3758a.

Are you sure this is the function that blows up, and not something else?

**Comment by jmartinm** [comment]
Breaking example https://github.com/inveniosoftware-contrib/invenio-matcher/pull/26
