### ISSUE TITLE
Update dotfiles and configuration to match current cookiecutter

### ISSUE THREAD

**Issue by jacquerie** [inveniosoftware-contrib/invenio-matcher#5]
This project started a while ago, so the latest and greatest improvements in https://github.com/inveniosoftware/cookiecutter-invenio-module are not there. I don't think there is a nice way of doing the upgrade, except copying and pasting the changes from there to here.

**Comment by kaplun** [comment]
@jacquerie can this be closed? Because @jalavik ported invenio-matcher to 3 in #11
